function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(6)=params(5)/(exp(params(13))*(params(5)+params(15)*params(4)*(1-params(2)*exp((-params(12))))));
    ys_(5)=ys_(6)^params(5);
    ys_(7)=((1-params(2)*exp((-params(12))))*ys_(5))^(-params(3))*(1-exp(params(13))*ys_(6))^(params(4)*(1-params(3)));
    ys_(8)=params(5)*ys_(6)^(params(5)-1)/params(15);
    ys_(9)=params(15);
    ys_(12)=0;
    ys_(10)=0;
    ys_(11)=exp(params(14)+params(12)*params(3))/params(1)-1;
    ys_(13)=ys_(5);
    ys_(16)=ys_(12);
    ys_(15)=ys_(10);
    ys_(17)=ys_(11);
    ys_(14)=0;
    ys_(18)=0;
    ys_(19)=params(13);
    ys_(20)=0;
    ys_(21)=params(12);
    ys_(22)=0;
    ys_(23)=0;
    ys_(24)=params(14);
    ys_(1)=exp(params(12));
    ys_(2)=1+ys_(11);
    ys_(3)=exp(params(14));
    ys_(4)=exp(params(14));
    % Auxiliary equations
end
